### PR TITLE
Add breathe_doxygen_config_options

### LINKED ISSUE #214: Passing config file options to Doxygen with autodoxygenindex
Right now, it is seemingly impossible to pass custom config options to `autodoxygenindex`'s config file template, making it impossible to, for instance, add an [EXCLUDE_SYMBOLS](http://stackoverflow.com/a/3733023/2097780) directive.

My idea is to have something like:

```
.. autodoxygenindex::
   :project: abc
   :config: ABC=124
```

but that might not work. I can try a PR of you'd like.

### PR DESCRIPTION
**Pull request by kirbyfan64**
Closes #214. I've never even *touched* a Sphinx extension before, so I might be doing something wrong. :O

### CODE REVIEW

**Comment by michaeljones** [comment]
Thanks for this, especially for including documentation as well. Kind of you to take the time.

I'm keen to tweak a couple of things, I'll try to do that soon and get this merged.

Thanks again,
Michael

**Comment by michaeljones** [comment]
I'm sorry for the lack of update. Life has been a little busy. Hoping to get around to it soon now.

**Comment by kirbyfan64** [comment]
@michaeljones It's fine. :) If you want, you can tell me what needs tweaking, and I can try it.

**Comment by michaeljones** [comment]
Hi, so I've just merged your changes and a small tweak. I can't apologise enough for taking so long over this. The change I made is tiny but so subjective that I don't like asking for it to be done as it feels like a personal preference thing more than anything. So I wanted to do it myself but totally failed to take the 15 mins required to think it through and do it. I'm really sorry. What's more, you were only following the code that was already there! I was the one that created the pattern that I didn't like and wanted to change :/

So I'm very sorry. Thanks for the excellent change and for the update to the documentation. I really appreciate the work.

**Comment by kirbyfan64** [comment]
@michaeljones There's nothing really to apologize for. :)

**Pull request merged**
