### PR TITLE
Fix for issue #200

### PR DESCRIPTION
**Pull request by olitheolix**
Doxygen's parameter descriptions are now rendered as inline text instead of as a new paragraph.

### CODE REVIEW

**Comment by olitheolix** [comment]
Travis did not like my changes :(

Does anyone have an idea what the problem might be?

**Comment by michaeljones** [comment]
Thank you very much for taking the time to have a go at this. I clearly failed to!

I'm afraid I can't say anything more helpful than 'the latex build is failing.' The Latex side of things is a dark art that I do not understand. It is less forgiving than HTML when it comes to nesting different types of layout so that might be an issue. I can't see much more right now but I can try to look at the weekend.

Thanks again!

**Comment by michaeljones** [comment]
Looks promising! Thanks for following that up. Not quite sure what the final issue is but I can have a look tomorrow if you're not sure what is causing it.

**Comment by olitheolix** [comment]
Thank you for pointing out that this was a problem with the LaTeX output. The problem was a missing white space before the docstring (to avoid fusing a LaTeX command with a word from the docstring). The second commit fixes this.

Now all builds pass except on Python 2.6, which fails because it cannot import the OrderedDict container. This seems unrelated to my commit, however. Any ideas?

**Comment by michaeljones** [comment]
Thanks again for this. Sorry I've let it slide.

On closer inspection there are legitimate doxygen `para` tags that are being rendered as `span` tags with this change. This means that multiple paragraphs in comments are being collapsed to single paragraph in the html output. We'll need to avoid this. I'll try to figure out how best.

**Comment by michaeljones** [comment]
See #285 for new attempt. Thanks for the input.

**Pull request closed without merging**
