### PR TITLE
Update CI scripts with new Sphinx versions

### PR DESCRIPTION
**Pull request by jakobandersen**
The Travis file seemed less up to date. Should it be removed? are the tests in it completely covered by the Github workflows?

### CODE REVIEW

**Comment by utzig** [comment]
This is in conflict, probably due to https://github.com/michaeljones/breathe/commit/75d0803e4add644ba9228a7839933d32a576ab58

**Comment by jakobandersen** [comment]
Thanks, it should be mergable now.

**Comment by jakobandersen** [comment]
Updated for Sphinx 3.2. Note that the Sphinx 3.1.x branch has now been closed, so the old Workflows will now always fail.

**Comment by vermeeren** [comment]
@jakobandersen I think it's fine to remove the Travis file completely, could you make the change in this PR? Will merge after.

**Comment by jakobandersen** [comment]
Done

**Comment by vermeeren** [comment]
Thanks, merged!

**Pull request merged**
