### PR TITLE
Support titles in verbatim blocks

### PR DESCRIPTION
**Pull request by lshamis**
https://github.com/michaeljones/breathe/issues/516
https://www.sphinx-doc.org/en/master/extdev/markupapi.html#viewlists

### CODE REVIEW

**Comment by lshamis** [comment]
@vermeeren I'm not sure how to replace the one at `tests/test_renderer.py:94`.

`nested_parse_with_titles` is a free floating function. `MockState.nested_parse` is a bound method.

```py
class MockState:
    def __init__(self, app):
        env = sphinx.environment.BuildEnvironment(app)
        env.setup(app)
        env.temp_data['docname'] = 'mock-doc'
        settings = frontend.OptionParser(
            components=(parsers.rst.Parser,)).get_default_values()
        settings.env = env
        self.document = utils.new_document('', settings)

    def nested_parse(self, content, content_offset, contentnode):  # <-- :94
        pass
```

**Comment by vermeeren** [comment]
@lshamis My bad, I wasn't fully awake when I posted it. I believe it is safe to remove the `nested_parse` in the test render, since no other Breathe code uses `nested_parse`. At the same time, perhaps functions called by Breathe call `nested_parse` internally, in which case we should probably not remove it.

Do you think it is better to keep the `nested_parse` in the test renderer just in case? If so this is good for merging really, I'll probably bump version after so you can use it right away.

**Comment by lshamis** [comment]
Removing `nested_parse` breaks the tests:
```
================================================ short test summary info ================================================
FAILED test_renderer.py::test_render_func - AttributeError: 'MockState' object has no attribute 'nested_parse'
FAILED test_renderer.py::test_render_typedef - AttributeError: 'MockState' object has no attribute 'nested_parse'
FAILED test_renderer.py::test_render_c_typedef - AttributeError: 'MockState' object has no attribute 'nested_parse'
FAILED test_renderer.py::test_render_c_function_typedef - AttributeError: 'MockState' object has no attribute 'nested_...
FAILED test_renderer.py::test_render_using_alias - AttributeError: 'MockState' object has no attribute 'nested_parse'
FAILED test_renderer.py::test_render_const_func - AttributeError: 'MockState' object has no attribute 'nested_parse'
FAILED test_renderer.py::test_render_lvalue_func - AttributeError: 'MockState' object has no attribute 'nested_parse'
FAILED test_renderer.py::test_render_rvalue_func - AttributeError: 'MockState' object has no attribute 'nested_parse'
FAILED test_renderer.py::test_render_const_lvalue_func - AttributeError: 'MockState' object has no attribute 'nested_p...
FAILED test_renderer.py::test_render_const_rvalue_func - AttributeError: 'MockState' object has no attribute 'nested_p...
FAILED test_renderer.py::test_render_variable_initializer - AttributeError: 'MockState' object has no attribute 'neste...
FAILED test_renderer.py::test_render_define_initializer - AttributeError: 'MockState' object has no attribute 'nested_...
FAILED test_renderer.py::test_render_define_no_initializer - AttributeError: 'MockState' object has no attribute 'nest...
============================================= 13 failed, 5 passed in 3.69s ==============================================
```

**Comment by vermeeren** [comment]
Suspected that could happen, everything is fine then as-is.

**Comment by vermeeren** [comment]
Released as 4.18.0.

**Pull request merged**
