### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by vitaut**
* Correct typo in PYTHONPATH
* Update imports for the new module structure

### CODE REVIEW

**Comment by michaeljones** [comment]
Cheers for catching this! I wonder why we weren't getting emails from travis? I were we and I just missed them?

**Comment by vitaut** [comment]
I was asking the same question myself. Looking at https://travis-ci.org/michaeljones/breathe/jobs/92576721, it appears that the tests are not run

```
$ make tests
make: Nothing to be done for `tests'.
```
because the target is called `test`, not `tests` and unfortunately this doesn't fail either because there is a directory named `tests`.

**Comment by vitaut** [comment]
Should be fixed in #230.

**Comment by michaeljones** [comment]
Thanks for debugging this mate. Kind of you and lazy of me. I'm checking it out now but for some reason `nosetests` is finding the `setup` function in `breathe/__init__.py` and trying to run it as set up for the tests. Not exactly sure why. Trying to investigate a bit.

I'll merge everything anyway but I'm a bit confused.

**Pull request merged**
