### PR TITLE
Improved parameter list rendering

### PR DESCRIPTION
**Pull request by michaeljones**
Starting with @olitheolix's work and trying to find something that works and feels like a reasonably clean implementation.

### CODE REVIEW

**Comment by michaeljones** [comment]
Happy enough to merge this if Travis is happy. I'd love a second opinion on it working. @olitheolix or @rweickelt or @mikepurvis? If you're still using Breathe :)

**Comment by michaeljones** [comment]
Takes over work from #273

**Comment by mikepurvis** [comment]
Haven't tried it, but the concept seems reasonable enough.

**Comment by olitheolix** [comment]
I just tried it on a local project and it works fine for me. Thank you for fixing this.

**Comment by michaeljones** [comment]
Thank you for checking it out. I'll merge it in later today.

**Comment by rweickelt** [comment]
@michaeljones I've just tried it out and it looks good to me. Thank you so much for the update.

**Comment by rweickelt** [comment]
One little note: The \param command allows exactly one paragraph. No need to check for multiple paragraphs. However, according to the [documentation](https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdparblock) it can be extended with \parblock \endparblock. Breathe seems to ignore this command. But since I never use \parblock, I am very happy with the current state.

**Comment by michaeljones** [comment]
Thanks for the research! Good to know. Kind of you to take the time. Yeah, I'll be a bit lazy with the `parblock` and wait for someone to request it.

This has been merged and released as 4.4.0.

**Pull request merged**
