### PR TITLE
Check that the file exists before trying to read it

### PR DESCRIPTION
**Pull request by michaeljones**
When attempting to see if it changes we have to make sure that it is
there before reading it. Not sure how this hasn't proven to be a problem
so far.

@vitaut, does this seem reasonable to you?

### CODE REVIEW

**Comment by vitaut** [comment]
LGTM although I'd catch an exception from `open` instead of checking if file exists to prevent a race.

**Comment by michaeljones** [comment]
Ah, yeah. Good call, I change that. Thanks!

**Comment by michaeljones** [comment]
Rebased on the the merged branch with '2.6' removed so we can have passing travis tests I hope.

**Comment by michaeljones** [comment]
Attempted to use with-statements to neaten it up. Shall I merge?

**Comment by t-b** [comment]
@michaeljones I've tested the latest version fo this PR with by test repository and it works.

I'm using python 2.7.9.

**Pull request merged**
