### PR TITLE
Handle default values in parameter declarations

### PR DESCRIPTION
**Pull request by vitaut**
This small PR adds handling of default arguments which were previously ignored in `get_param_decl`.

### CODE REVIEW

**Comment by michaeljones** [comment]
Sorry for the slow pick up. Looks good to me. Merge away if you like!

**Comment by vitaut** [comment]
Merged. Thanks for reviewing!

**Comment by zyv** [comment]
@michaeljones do you think you could make a release from master anytime soon? My doc builds are crashing due to this bug, but I can't really easily switch to using the git version easily due to pypa/pip/issues/373 :-/

**Comment by michaeljones** [comment]
I'm sure we can manage that soonish. @vitaut is more on the ball than me these days. @vitaut, are we in a good place to release?

**Comment by vitaut** [comment]
I think so. The renderer refactoring is mostly complete and it didn't result in any noticeable output changes.

**Comment by zyv** [comment]
@vitaut any news on that front? Thanks in advance!

**Comment by vitaut** [comment]
@zyv Do you mean default arguments? They should be working now.

**Comment by zyv** [comment]
@vitaut, I meant to ask whether a release can be cut that contains this pull request anytime soon. As I said, current master works just fine for me, which is great except that I'm having difficulties simply switching to git master from released version for unrelated reasons (pip bug).

**Comment by vitaut** [comment]
@zyv Unfortunately I won't have time to prepare a release in the next week or so, but maybe @michaeljones can help you?

**Comment by michaeljones** [comment]
I'm happy to do a release. Tomorrow evening (UK time) if that's cool? I should have time.

**Comment by michaeljones** [comment]
Hi, sorry, there is a release with this merged in already. 4.2.0 should have it: https://pypi.python.org/pypi/breathe/4.2.0

Is that ok? Or is there something more recent that you'd like?

**Pull request merged**
