### PR TITLE
Add templated struct function failing example

### PR DESCRIPTION
**Pull request by guyguy333**
This commit is linked to issue #219
Add a failing example with functions in a templated struct

Signed-off-by: Guillaume Delbergue <guillaume.delbergue@greensocs.com>

### CODE REVIEW

**Comment by michaeljones** [comment]
Thanks very much for this. I've pushed a branch called 'struct-function' that should fix the issue. Could you possibly test it out and make sure it works for you?

I've had a strange situation where I have a small doc set up that I use for testing and it is failing in there for some weird reason but it works for the main example documentation we have. I can't explain it. I'm just hoping it is some weird quirk :/

**Comment by michaeljones** [comment]
If you do come across a problem with your 'const MyClass &' example not working. You might want to try the `whitespace` branch I've just pushed. That fixes the issue I'm having in my test repository (which I get again if I make a new test repository, which is concerning!)

**Comment by vitaut** [comment]
So what's up with this PR? @guyguy333, does Michael's solution work for you?

**Comment by vitaut** [comment]
Merged as a part of #256. See also https://breathe.readthedocs.org/en/latest/members.html#struct-members

**Pull request closed without merging**
