### PR TITLE
demonstrate bug when adding namespace to a group

### PR DESCRIPTION
**Pull request by pwm1234**
With this pull request I extended the group.h example to add a namespace to a group, which demonstrates a bug when breathe shows the documentation for the group. All entries in the namespace a duplicated for each namespace in which they are contained. This problem is not present in doxygen's html output.

Here is a converted sample of the output, which shows that MyClass2 three times. Once for its first class entry in mygroup, once for being in namespace 1, and again for being in ns1::ns2.

Unfortunately, I have no idea how to fix this problem, but I am hopeful that providing this example will help you fix it! :-)
## Basic Example

The plain `doxygengroup` directive will output the
group name and description and any top level publicly visible members of
the group.

```
.. doxygengroup:: mygroup
   :project: group
```

It produces this output:

 _group_ `mygroup`
:   This is the first group.

```
Functions

 void `groupedFunction`
:   This function is in MyGroup.

 *class* `GroupedClassTest`
:   *\#include \<group.h\>*

    first class inside of namespace

 *class* `MyClass1`
:   *\#include \<group.h\>*

    A class in ns1.

 *class* `MyClass2`
:   *\#include \<group.h\>*

    A class in ns1::ns2.

    Detailed description of function2.

    member group name

    Description of member group goes here

 *namespace* `ns1`
:   outer namespace

     *class* `MyClass1`
    :   *\#include \<group.h\>*

        A class in ns1.

     *namespace* `ns2`
    :   inner namespace

         *class* `MyClass2`
        :   *\#include \<group.h\>*

            A class in ns1::ns2.

            Detailed description of function2.

            member group name

            Description of member group goes here

 *namespace* `ns2`
:   inner namespace

     *class* `MyClass2`
    :   *\#include \<group.h\>*

        A class in ns1::ns2.

        Detailed description of function2.

        member group name

        Description of member group goes here
```

### CODE REVIEW

**Comment by michaeljones** [comment]
@pwm1234, thanks for getting such an excellent report! Definitely looks like less than ideal behaviour from Breathe. We'll look into getting that fixed.

Do you have an opinion on what the output should look like? I guess ideally it would show the contents in their namespaces, nested appropriately without any duplication? So this:

```
 *group* `mygroup`
:   This is the first group.

    Functions

     void `groupedFunction`
    :   This function is in MyGroup.

     *class* `GroupedClassTest`
    :   *\#include \<group.h\>*

        first class inside of namespace

     *namespace* `ns1`
    :   outer namespace

         *class* `MyClass1`
        :   *\#include \<group.h\>*

            A class in ns1.

         *namespace* `ns2`
        :   inner namespace

             *class* `MyClass2`
            :   *\#include \<group.h\>*

                A class in ns1::ns2.

                Detailed description of function2.

                member group name

                Description of member group goes here

```

Does that seem right to you?

Thanks for trying the project. I hope you are happy with it otherwise.

**Comment by pwm1234** [comment]
Let me first say Thanks for your work on Breathe--I find it quite helpful!

I believe what you are suggesting is what doxygen shows on its group page. The rationale seems to be if a namespace is in a group, everything in the namespace is in the group. But I would prefer at least the option to choose a different presentation. I would like the breathe doxygengroup directive to display a single entry for a namespace and not list all the contents of the namespace. I can use the doxygennamespace directive when want to show all the contents of the namespace. Perhaps having an option *expand-namespace* would enable control this behavior and satisfy both use cases.

**Comment by t-b** [comment]
@pwm1234 Do you still have the code for this PR? Github thinks it's not present anymore. If yes please rebase to master and force push.

**Comment by t-b** [comment]
@pwm1234 Thanks. I'll pick the changes then manually and create a new PR.

**Comment by t-b** [comment]
@pwm1234 The resurrected branch is at https://github.com/t-b/breathe/tree/namespace_bug. If someone wants to create new PR from that please document in the commit message what is not working. I can't figure that out.

**Pull request closed without merging**
