### PR TITLE
Update comparison script

### PR DESCRIPTION
**Pull request by michaeljones**
Hey @vitaut,

I noticed that the comparison script needed to be a bit more careful about rebuilding the examples and cleaning out the old build. Just made a pull-request so it can fit in with your development where you'd like.

Michael

### CODE REVIEW

**Comment by vitaut** [comment]
Hi Michael,

Thank you for letting me know about this script and updating it, this is very useful. I was blindly unaware of its existence. =)

Cheers,
Victor

**Comment by michaeljones** [comment]
It is not well advertised :) But it is about as close to tests as we have. I find it very useful to check that changes haven't had unexpected effects.

**Comment by vitaut** [comment]
I've already tried it on the new branch and it's awesome (as expected - no changes to output). I wonder how I managed not to break everything without such script =).

**Comment by michaeljones** [comment]
I'm going to merge this is into master just so it is there.

**Pull request merged**
