### PR TITLE
Add breathe_show_enumvalue_initializer option

### PR DESCRIPTION
**Pull request by yamt**

### CODE REVIEW

**Comment by yamt** [comment]
this PR implements https://github.com/michaeljones/breathe/issues/578

**Comment by utzig** [comment]
You should probably squash your commits.

**Comment by yamt** [comment]
@utzig ok. done

**Review by utzig — APPROVED** [review]

**Review by vermeeren — APPROVED** [review]

**Comment by vermeeren** [comment]
@yamt Thanks for the patch, is it desired to have a new Breathe release for this?

**Comment by yamt** [comment]
@yamt yes, as we are using a released version to render our document. not urgent at all though.

**Comment by vermeeren** [comment]
@yamt fyi I have released v4.22.0 just now containing this patch.

**Comment by yamt** [comment]
@vermeeren thank you!

**Pull request merged**
