### PR TITLE
Show the initializer of defines

### PR DESCRIPTION
**Pull request by Tiwalun**
Basic support to show the initializer of defines. (see #311).

Multi-line defines are currently shown on a single line.

### CODE REVIEW

**Comment by michaeljones** [comment]
Looks great! Merged.

Thanks for doing such a complete set of changes with tests everything. Really helps!

**Comment by michaeljones** [comment]
I've made you a collaborator. I hope that's alright. If you get a chance in the future, just push branches directly to the repository. Still keen to have them reviewed by someone before they make it into `master` but very happy to see your contributions :)

**Comment by dean0x7d** [comment]
Having this on by default (without a way to turn off) is a bit unfortunate. Macros usually hide some implementation detail which shouldn't be in the docs. Squishing multiline macros to a single line makes it look even more cryptic. Any chance to make it optional as originally proposed in #311?

**Comment by Tiwalun** [comment]
@dean0x7d If always showing this is a problem for you, I will add an option to turn it off/on.

**Comment by dean0x7d** [comment]
That would be great. Thanks!

**Comment by Tiwalun** [comment]
I've created a pull request for the option in #323

**Pull request merged**
