### PR TITLE
Add failing doxygen example using anchor/ref

### PR DESCRIPTION
**Pull request by t-b**
"FancyConstants" in the function comment is expected to be a link, but
currently is just plain text.

### CODE REVIEW

**Comment by t-b** [comment]
@SylvainCorlay Is that ready to merge?

**Comment by SylvainCorlay** [comment]
@t-b looking at it now. 

Can you please elaborate on this? You are showing a case of failure?

**Comment by t-b** [comment]
@SylvainCorlay Yes this PR adds an `@anchor/@ref` example which breathe does currently not support.

**Comment by t-b** [comment]
*ping*

**Comment by SylvainCorlay** [comment]
Do you intend on making breathe support `@anchor`?

**Comment by t-b** [comment]
@melvinvermeeren Rebased.

**Comment by melvinvermeeren** [comment]
@t-b If I understand correctly anchors currently do not work at all, which means it is actually an enhancement as it is a new feature. Should probably open up an issue for this, does that make sense?

**Pull request closed without merging**
