### PR TITLE
Adapt to upcoming Sphinx 2.0

### PR DESCRIPTION
**Pull request by jakobandersen**
Initial steps to adapt to the upcoming version of Sphinx (2.0).

### CODE REVIEW

**Comment by svenevs** [comment]
Thank you @jakobanderson this is **really** helpful! I was under the impression that we needed to switch to `pytest` in order for the tests to run / user the sphinx fixtures. But it appears this is not the case.

Does this supersede #410?

**Comment by melvinvermeeren** [comment]
Thanks a lot for all submitting all these patches. I have been rather busy for a while so my responses to Breathe-related things have been slow. PR #410 seems ok to me, so I'll merge it now.

Indeed long term the plan for an eventual Breathe 5 is to rewrite and/or refactor major parts of the sometimes overly complex logic and let Sphinx itself handle things cleanly. As you said I am sure this will fix several open bugs and quirks. Thanks again!

**Comment by jakobandersen** [comment]
If you trigger a rebuild in Travis it should(TM) succeed now that Sphinx 2.0 has been released.

**Comment by meeludwig** [comment]
Hi michaeljones,
maybe I have found a rather deep & simple isse, rather breathe and not sphinx or doxygen. 
https://github.com/sphinx-doc/sphinx/issues/6146
Thanks , michael

**Comment by jakobandersen** [comment]
Doh, nevermind, 2.0 is _close_ to be released, but it will take a few more weeks.

**Comment by t-b** [comment]
@jakobandersen Can you push to trigger a build?

**Comment by jakobandersen** [comment]
_Now_ I think the PR should be ready to merge :-)

**Comment by melvinvermeeren** [comment]
Looks good to me. Just to make sure: merge this and release as v4.13.0?

**Comment by amirmasoudabdol** [comment]
I'm wondering if there is still an issue with this PR? I'm using it for a while and it works fine, it'd be nice to merge it and have a new version :-) If there is an issue, I'm happy to help btw.

**Comment by Milerius** [comment]
can we merge this ?

**Comment by melvinvermeeren** [comment]
I have released v4.13.0 containing this fix, all should be good now.

**Comment by Milerius** [comment]
@melvinvermeeren is it ready in pip ?

**Comment by melvinvermeeren** [comment]
@Milerius Should be up now, the upload was running at the time you posted.

**Comment by Milerius** [comment]
@melvinvermeeren Thank's a lot i made the upgrade

**Pull request merged**
