### PR TITLE
Fix flake8 warnings (E305)

### LINKED ISSUE #297: CI tests fail on master due to whitespace
This makes all pull requests be marked as failing, which is not useful.

`breathe/parser/compound.py` is the culprit

### PR DESCRIPTION
**Pull request by eric-wieser**
Cherry-picked from #288. Fixes #297

### CODE REVIEW

**Comment by vitaut** [comment]
LGTM!

**Comment by vitaut** [comment]
@eric-wieser Could you rebase your other PRs?

**Comment by eric-wieser** [comment]
@vitaut : Yep, that was my plan

**Comment by eric-wieser** [comment]
@vitaut: Done

**Comment by vitaut** [comment]
Nice =)

**Pull request merged**
