### PR TITLE
Fix domain detection when rendering groups.

### PR DESCRIPTION
**Pull request by rkapl**
Groups themselves do not have any filenames, so the detection must be
done on lower level. However, compound signatures were rendered in the
context of the group, with the default domain (C++) . This lead to all kinds of
missed reference from C domain code.

For example, let's have in `test.h`:
`/** @ingroup test */ typedef struct {} example_t;`
and `/** @ingroup test */ void user(example_t arg);`

Breathe is configured to recognize `.h` files as C domain. If you use `doxygenfile`, the links work correctly. If you use `doxygengroup`, the the arguments of the `user` function are not links and `example_t` is in the C++ domain.

### CODE REVIEW

**Comment by rkapl** [comment]
Sorry, please also add `/** @defgroup test */`. To the example file.

**Comment by melvinvermeeren** [comment]
Thanks for the quick reply.

screenshot_20180522_215804

Just to make sure I get it properly, the only difference is that in `void user(example_t arg)` the `example_t` type is now in the correct domain and thus a link, right?

**Comment by rkapl** [comment]
Yes, the point was to make these links work. Maybe it also affects something else, but I don't know.

**Comment by melvinvermeeren** [comment]
Merged, thank you for the PR.

**Pull request merged**
