### PR TITLE
support for MD block quotes with attribution(s)

### LINKED ISSUE #758: [request] support block quotes
Since Doxygen supports the markdown syntax, writing a block quote in src comments (and md files) would be done like so
```md
> This is a block quote
>
> -- Anonymous
```
Note the space between the `>` and the quote's text is required per Doxygen's manual on markdown support (see link below).

In doxygen's XML output, this would look like
```xml
<para>
    <blockquote>
        <para>This is a block quote.</para>
        <para><ndash/> Anonymous </para>
    </blockquote>
</para>
```
Currently, it seems like breathe ignores the `blockquote` tag entirely (during XML parsing of `para` tags). Just for completeness, the HTML output from an equivalent rST block quote looks like
```html
<blockquote>
  <div>
    <p>This is a block quote.</p>
    <p class="attribution">—Anonymous</p>
  </div>
</blockquote>
```
Clearly, An attribution in a block quote also needs to be accounted for.

## Some helpful links
- [rst specs on block quotes](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#block-quotes)
- [doxygen manual on markdown syntax using block quotes](https://www.doxygen.nl/manual/markdown.html#md_blockquotes)

### PR DESCRIPTION
**Pull request by 2bndy5**
resolves #758 

See issue thread for more details (includes XML, HTML, and MD snippets).

### CODE REVIEW

**Review by vermeeren — APPROVED** [review]
@2bndy5 Thanks for all your patches recently! This one was the final non-WIP PR in queue, glad to have caught up with it all today. Will do my best to respond quick to coming patches.

**Comment by 2bndy5** [comment]
Just wanted to voice my gratitude for all the work done today. @vermeeren You went above and beyond my expectations concerning git history and merge conflicts! Sorry, I wasn't more responsive during this streak of productivity (I was sleeping).

Given that there is only 1 PR at this time, I think I'll start work on a submission that will reduce the warnings/errors in the docs build logs. @michaeljones I noticed there's a new project logo being used. Any objections to using that branding for the docs' favicon (instead of RTD's default)? I can't decide if this pursuit is worthy of an issue or a discussion (kinda leaning toward a new issue).

**Comment by vermeeren** [comment]
@2bndy5 Thanks for the feedback! Perfectly fine to submit PRs as you see, also for the logo. No need for issue imo as it's kinda an obvious improvement.

Cheers

**Comment by 2bndy5** [comment]
@michaeljones Can I interest you in switching to [the furo theme](https://pradyunsg.me/furo/quickstart)? It supports light/dark/system schemes out of the box and displays the ToC in an independent menu. I discovered it when reading the docs for pip, setuptools, and sphinx_design.

The PR about dealing warnings/errors from sphinx and doxygen is almost ready. Though, if we use furo theme, then the `.. contents::` directive is useless/redundant.
image

**Comment by michaeljones** [comment]
I think I'd be happy moving to that. I'd like to try to unify the visuals around the different parts of Breathe. Mostly using the logo and maybe trying to align colours between the docs and the website a little. The website colours aren't final though so we can adjust those. 

Are you happy to provide a PR with that change?

**Comment by 2bndy5** [comment]
I'm about to submit a PR with the theme change, pygments typing, and enable `-W` option for sphinx-build command (I fixed 400+ warnings in the doc build log).

I would've suggested the sphinx-immaterial them (which I help maintain), but there's a CSS problem with displaying C/C++ API signatures.

As far as the colors for the website, is the code hosted somewhere? I'd like to propose a CSS change that compensates for light & dark theme (via media query). If viewed with the dark reader extension enabled, then the current website's text has a 💩 brown background.

**Comment by michaeljones** [comment]
It is hosted on a server I run and the code is in another repo. I guess we could consider moving the website code here to start opening up avenues for improvement. Or I can invite you to the other repo. Not sure of the pros & cons. I'll start with the latter and we'll see.

**Pull request merged**
