### PR TITLE
Kill matchers as they are not used any more

### PR DESCRIPTION
**Pull request by vitaut**
Matchers have been replaced with finder filters.

### CODE REVIEW

**Comment by vitaut** [comment]
And one more commit to reduce code duplication in compound renderering.

**Comment by michaeljones** [comment]
Nice one. Looks good to me. Good call on the common base class.

**Comment by michaeljones** [comment]
Merge away.

**Comment by vitaut** [comment]
Merged in https://github.com/michaeljones/breathe/commit/cfddaf892d0e7db9893182233ae50c92e7978fd4. Thanks for reviewing.

**Pull request closed without merging**
