### PR TITLE
Update travis

### PR DESCRIPTION
**Pull request by t-b**

### CODE REVIEW

**Comment by D4N** [comment]
You seem to have hit the same issue as reported in #465.

**Comment by t-b** [comment]
Should be retried after #472 is merged.

**Comment by melvinvermeeren** [comment]
Rebased your commits on top of master.

**Comment by melvinvermeeren** [comment]
Works fine now, so will merge to master. Will update README afterwards.

**Comment by t-b** [comment]
@melvinvermeeren Thanks!

**Pull request merged**
