### PR TITLE
Add '=' to the initializer if Doxygen doesn't

### PR DESCRIPTION
**Pull request by vitaut**
This PR fixes rendering of enumeration values on Doxygen 1.7.6 which doesn't put `=` in initializers.

### CODE REVIEW

**Comment by vitaut** [comment]
And one more small fix for namespace-qualified enums.

**Comment by michaeljones** [comment]
Looks good to me :) Good catch.

**Comment by vitaut** [comment]
Thanks, Michael. While I'm in bug fixing mode, here's another commit that fixes handling of nested namespaces in get_fully_qualified_name. As it turned out `node_stack` does not always contains parent namespaces. For example if I have `.. doxygenenum:: a::b::C` there is only one namespace node on stack.

**Comment by vitaut** [comment]
So if there are no objections regarding the last commit, I'll merge this.

**Comment by michaeljones** [comment]
Yeah, looks good. Cheers for updating the comment to explain. Sorry for the slow response!

**Comment by vitaut** [comment]
No problems. I should have probably submitted the last commit as a separate PR, but I noticed your comment only after pushing. Anyway, this is merged now.

**Pull request merged**
