### PR TITLE
Add multiple Sphinx version & flake8 coverage

### PR DESCRIPTION
**Pull request by michaeljones**
Hi @vitaut,

I thought I'd take a stab at getting travis to test both Sphinx 1.2.* and 1.3.* which seems to be working brilliantly thanks to your work.

I then thought we could start introducing `flake8` checks to try to keep the code closer to PEP-8 compliance. I'm sorry I never took it that seriously in the early days of the project so there is a bit of debt to work through. I've started off with a subset of files with the hope of expanding that group as we work on them.

One trouble with lots of white space PEP-8 related changes is that it plays havoc with merges. I'm not sure if you're currently working on anything but if you are and it clashes please feel free to merge or rebase in a way which keeps all your changes and loses this for the moment. There are no logic changes here so it is much easier to redo PEP-8 compliance than actually useful code.

Cheers,
Michael

### CODE REVIEW

**Comment by vitaut** [comment]
Hi @michaeljones,

Nice work. I'm not doing anything with Breathe at the moment so there are no conflicts, but thanks for letting me know.

BTW now that Sphinx 1.3 is finally released, maybe its a good time to release a new version of Breathe?

Best regards,
Victor

**Comment by michaeljones** [comment]
@vitaut, sounds good, time for Breathe 4?

**Comment by vitaut** [comment]
:+1:

**Comment by vitaut** [comment]
@michaeljones I hope you are not waiting for my or anyone else's approval to merge this ;-). I'd very much like to see this merged soon to start working with a cleaner codebase.

**Comment by michaeljones** [comment]
Ha, cheers for the prompt mate. I'm afraid I've been distracted but I'm very happy to merge. Will do so now!

**Pull request merged**
