### PR TITLE
Remove unneeded type: ignore annotations

### PR DESCRIPTION
**Pull request by jakobandersen**
mypy seems to have gotten more clever.

### CODE REVIEW

**Comment by 2bndy5** [comment]
if you remove the implicit typing from 

https://github.com/michaeljones/breathe/blob/d38542ff6a509f80fa75fdf94a4949cee635925e/breathe/renderer/sphinxrenderer.py#L1864

then mypy can infer the type from https://github.com/michaeljones/breathe/blob/2e160cb5ead7e8be9644372e379e394bfb7a21a3/breathe/renderer/target.py#L10

**Comment by 2bndy5** [comment]
I also had to do somethings to get the pygments API typing.

```diff
--- breathe/filetypes.py
+++ breathe/filetypes.py
- import pygments  # type: ignore
+ from pygments.lexers import get_lexer_for_filename
+ from pygments.util import ClassNotFound


 def get_pygments_alias(filename: str) -> Optional[str]:
     "Find first pygments alias from filename"
     try:
-        lexer_cls = pygments.lexers.get_lexer_for_filename(filename)
-        return lexer_cls.aliases[0]
+        lexer_cls = get_lexer_for_filename(filename)
+        return lexer_cls.aliases[0]  # type: ignore
-    except pygments.util.ClassNotFound:
+    except ClassNotFound:
         return None
```

and add
```txt
types-Pygments
```
to requirements/development.txt

**Comment by jakobandersen** [comment]
@2bndy5, there are indeed other typing issues that should be fixed in various places. Locally my mypy also complains about more stuff, but maybe it's because it's an older Python version than in the CI.
For now I'll just make the CI green :-).

**Comment by michaeljones** [comment]
> I also had to do somethings to get the pygments API typing.
> 

Interesting to see! I struggled to understand how to make mypy happy with that.

**Pull request merged**
