### PR TITLE
Attempt to fix mypy issues that are failing on CI

### PR DESCRIPTION
**Pull request by michaeljones**
I'm quite new to mypy having been away from the Python ecosystem for a while now but given the information I could get from the docs and the state of the docutils typings and the way we've written this code, I think these are reasonable changes to make.

### CODE REVIEW

**Comment by michaeljones** [comment]
All green. A beautiful thing.

**Comment by michaeljones** [comment]
I'm in the odd position of not knowing if I can just merge this for a repo that is under my name. I think it is all good but happy for a second opinion if anyone is around.

**Review by utzig — APPROVED** [review]
LGTM

**Comment by michaeljones** [comment]
Thank you @utzig

**Pull request merged**
